### ISSUE TITLE
Requesting permissions with reduce not working

### ISSUE THREAD

**Issue by andreheuer** [tb1337/paperless-api#161]
Hi,

during my work with pypaperless (which evolved very well!), I stumbled upon the following issue: I would like to get the permissions of the tags I have filtered.

However, it seems that the permissions are not received and the `has_permissions` attribute remains `false` (but expected to be `true`): 

```
tag_filter = {
        "name__istartswith": "H",
}
paperless.tags.request_permissions = True
async with paperless.tags.reduce(**tag_filter) as tag_filtered:
  async for tag in tag_filtered:
    if tag.has_permissions:
      # should be true, but is false
```

**Comment by tb1337** [comment]
I gonna check that after holidays. Thank you
