### ISSUE TITLE
Fails to get paginated results if paperless-ngx is behind nginx proxy with https only

### ISSUE THREAD

**Issue by abbbi** [tb1337/paperless-api#2]
Hi,

attempting to get paginated results via pypaperless fails, if the target system is behind nginx proxy and exposed via https only. It seems the the API response might include the wrong hostname in the "next" key,
See https://github.com/paperless-ngx/paperless-ngx/issues/3130 for details.

**Comment by tb1337** [comment]
Should work with the new update.
