### ISSUE TITLE
[Feature request] API endpoints for bulk-editing

### ISSUE THREAD

**Issue by madduck** [tb1337/paperless-api#213]
PNGX has [an API endpoint for bulk-editing of documents](https://docs.paperless-ngx.com/api/#bulk-editing), and another [generic endpoint for objects](https://docs.paperless-ngx.com/api/#objects).

Please consider adding those to your lovely API wrapper!

**Comment by tb1337** [comment]
Okay, thank you. I will check how that could be baked into pypaperless.
