### ISSUE TITLE
No meaningful error message when trying to update a custom field of type Integer

### ISSUE THREAD

**Issue by marcelbrueckner** [tb1337/paperless-api#295]
When trying to update an custom field of type `Integer` with a value that's not an Integer, the error message in the exception raised by pypaperless is not very helpful:

```
Paperless: custom_fields - {}
```

Of course it's my fault trying to set an string value :) However, a better error handling would of course be an advantage for faster investigating the error cause.

Paperless-ngx (I'm still on v2.5.3 btw) gives an hint in its error response but pypaperless' `JsonResponseWithError` class doesn't properly extract it:

```
{'custom_fields': [{'non_field_errors': ['Enter a valid integer.']}, {}, {}]}
```

Here's an excerpt of my "debug session" in case it helps:

```python
(Pdb) l 20, 40
 20  
 21     class JsonResponseWithError(PaperlessError):
 22         """Raise when Paperless accepted the request, but responded with an error payload."""
 23  
 24         def __init__(self, payload: Any) -> None:
 25             """Initialize a `JsonResponseWithError` instance."""
 26             key: str = "error"
 27             message: Any = "unknown error"
 28  
 29 B           if isinstance(payload, dict):
 30                 key = "error" if "error" in payload else set(payload.keys()).pop()
 31                 message = payload[key]
 32                 if isinstance(message, list):
 33                     message = message.pop()
 34  
 35  ->         super().__init__(f"Paperless: {key} - {message}")
 36  
 37  
 38     # Models
 39  
 40  
(Pdb) p payload
{'custom_fields': [{'non_field_errors': ['Enter a valid integer.']}, {}, {}]}
(Pdb) p key
'custom_fields'
(Pdb) p message		# at line 31
[{'non_field_errors': ['Enter a valid integer.']}, {}, {}]
(Pdb) p message		# at line 33
{}
```

**Comment by tb1337** [comment]
You are right, I have to improve that. On my list now. Thanks for for your debugging, it will help a lot!

**Comment by tb1337** [comment]
PR is on the way, still need to improve coverage and address mypy warnings. After that I'll throw it out.

**Comment by marcelbrueckner** [comment]
Thanks, just updated `pypaperless` to v3.1.14 and the error message is now easier to understand 👍 

```
Paperless [custom_fields -> non_field_errors]: Enter a valid integer.
```
