### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by jfrcom** [tb1337/paperless-api#5]
Greetings,

I have recently come across this API wrapper and I was very excited to test it out. Unfortunately, I have encountered an issue as it does not seem to be functioning properly for me. Every time I attempt to use it, I receive a 403 Forbidden error with the following message: `aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL`.

I have double-checked and I am using the same token in both the Python file and the curl command, but for some reason, the Python implementation is not working while the curl command is functioning without any issues.

```
curl --request GET \
  --url <my_paperless_instance> \
  --header 'Accept: application/json; version=2' \
  --header 'Authorization: Token <my_token>'
```

Any idea why that is?

**Comment by tb1337** [comment]
Please provide your Python code snippet without actual credentials.

**Comment by ict** [comment]
You need to add `/api` to the URL, the library does not do this.

**Comment by tb1337** [comment]
In the new version, you just need to provide your paperless url and the lib adds /api/ by itself.
