### ISSUE TITLE
[feature request] maintain custom fields at a document

### ISSUE THREAD

**Issue by tzepter** [tb1337/paperless-api#54]
Would it be possible to add crud functionality for custom fields at a document?

**Comment by tb1337** [comment]
Yes, I wan to add that. Currently working on the Paperless-ngx update (they migrated consumption templates to workflows).

**Comment by tzepter** [comment]
Thx!

**Comment by tb1337** [comment]
Handling is very tricky, I have to refactor that in the future. Be sure to read the docs. But currently it works.
I have to rebuild the complete CustomField feature of *PyPaperless*, since it doesn't fit in the current architecture of the lib.

**Comment by tzepter** [comment]
My stuff with CustomFields (create, create at documents, search for it) works fine. :)
