### ISSUE TITLE
FR: Support filename during document upload

### ISSUE THREAD

**Issue by andreheuer** [tb1337/paperless-api#59]
Currently, the original filename is always "document" when creating a new document using the API.

I would like to request to define the filename during creation of a new document, i.e.:
1. Extend Document post by `filename: str | None = None`
2. Change `create` or `dataclass_to_dict` method of `DocumentController` to check if filename is present. If it is present, then set `form.add_field("document", obj.document, filename=obj.filename)`. Otherwise keep current logic.

BTW: I got the dev container up and running. Might be I will get a PR in place.

**Comment by tb1337** [comment]
Ah cool :) sharing the development environment is so much less a pain with devcontainers. I really love it and use that not only for python projects.  

Adding that could be tricky as I moved the actual form code away from the controller. It is now in the paperless class.

But I’m unhappy with the current architecture of Paperless (responsible for sending stuff and exceptions)/Controller (data transformation and endpoint specifics) /Model (actual data) anyway. Currently playing with other approaches like metaclasses.

**Comment by tb1337** [comment]
See #62
