### ISSUE TITLE
Duplicates in get_documents()

### ISSUE THREAD

**Issue by splifter** [tb1337/paperless-api#6]
Hi,

i've found something really strange and i'm not able to make sense out of it. I'm not sure if it is an paperless issue or an issue of the wrapper. Hope to get some help in identifying the source of my issue.
I use below code to receive all documents. The total number of results adds up with the one i see in the paperless frontend but there are duplicate entries inside.

> paperless = Paperless(PAPERLESS_URL, PAPERLESS_TOKEN)
docs = paperless.get_documents()
dl = list()
for d in docs:
    dl.append(d.id)
dl.sort()
print(dl)
print(f'Total results: {len(dl)}')
print(f'Unique results: {len(list(dict.fromkeys(dl)))}')

Result

> [1, 1, 2, 3, 4, 4, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 25, 25, 26, 27, 28, 29, 29, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35, 35, 36, 36, 37, 37, 38, 38, 39, 40, 40, 41, 42, 42, 43, 43, 44, 44, 45, 46, 47, 47, 48, 48, 49, 50, 50, 51, 52, 53, 54, 55, 56, 58, 59, 60, 61, 62, 64, 67, 69, 70, 72, 73, 74, 75, 76, 77, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 93, 94, 96, 97, 99, 100, 101, 102, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 116, 118, 119, 120, 121, 122, 125, 126, 127, 128, 129, 130, 134, 135, 136, 138, 140, 141, 143, 144, 145, 147, 148, 151, 152, 154, 155, 156, 157, 158, 159, 160, 161, 163, 167, 169, 171, 172, 173, 174, 175, 176, 178, 179, 180, 181, 182, 183]
Total results: 183
Unique results: 149

Anyone havong the same result?

**Comment by tb1337** [comment]
I did a complete rewrite of the library to async. Also re-implemented the endpoints and method. I would close your issue in favor of the upcoming release.
