### ISSUE TITLE
Useful task.result

### ISSUE THREAD

**Issue by tzepter** [tb1337/paperless-api#61]
I want to get a failed task info like "document: Not consuming document: It is a duplicate of XXX (#143)" to log it. The result attribute at the model class Task is of type <str>. That means in my case that task.result looks like that "'<traceback object at 0x7efc655b3100>". I guess that info is nothing explorable. Is it possible to return the traceback or the fundamental error description?

**Comment by tb1337** [comment]
The `Task` class stores a `result` as a string, a Task from the Paperless api should look like that:

![image](https://github.com/tb1337/paperless-api/assets/38990875/b54f0d72-418d-407f-8674-ad245cab4afa)

Could you provide the json that is returned by your Paperless api for your requested Task?

**Comment by tzepter** [comment]
> I have no Computer access in the Moment. But for short: pls try to upload a binary executable that cannot be handled by paperless. The result should be a traceball which is transfered as '<object under the address ...>.'. Sometimes a real error message is returned in this case. Maybe it is a timing problem.

**Comment by tb1337** [comment]
Cannot reproduce. Paperless responds with 415 Wrong Media when sending non pdf/image/office files. I tested with v3 against a dev host with the latest Paperless-Ngx release.

**Comment by tzepter** [comment]
The original case was the double upload of a document. The task in paperless recognizes this situation based on the checksum of the document and fails on the second attempt - at least for me. Instead of the error message, however, I receive the object address of the traceback.

**Comment by tb1337** [comment]
Okay, whatever happened there, v3 seems to fix that. I forced uploading a document twice, requested the `task.result` every 0.25 seconds and printed the it. As you can see, it seems to work now :)

![image](https://github.com/tb1337/paperless-api/assets/38990875/19b79c00-34be-4758-9a49-3bc73eb7c36d)

**Comment by tzepter** [comment]
Fine! Thx.
