### ISSUE TITLE
MIME types beyond pictures and PDF

### ISSUE THREAD

**Issue by tzepter** [tb1337/paperless-api#62]
I wonder how a non-pdf and non-picture file is to upload. The paperless ngx-API does it:

```
resp = httpx.post(host + "/api/documents/post_document/",
                  headers={"Authorization": "Token " + token, "Accept": "application/json; version=3"},
                  files={'document': (
                      'test.ods', open('./test.ods', 'rb'), 'application/vnd.oasis.opendocument.spreadsheet')},
                  data={"title": "My first upload", "created": "2023-12-21"},
                  verify='./cacert.pem')
```
With pypaperless I do the following:

```
        with open(file_path, "rb") as doc_file:
            data = doc_file.read()
        new_document = DocumentPost(
            document=data,
            title=title,
            created=doc_date,
            correspondent=None,
            document_type=None,
            tags=[],
            archive_serial_number=None
        )
```
I cannot see the chance to set the Mime type or the document original name. Can you help me?

**Comment by tzepter** [comment]
PS: The task result in Paperless - when I upload bytes of an ods file is:

`document: Error occurred while consuming document document: Error while converting document to PDF: Client error '400 Bad Request' for url 'http://gotenberg:3000/forms/libreoffice/convert'`

**Comment by tzepter** [comment]
I have to add that the above mentioned httpx-Post does work without a MIME type argument, too. Paperless checks the type with inspecting the content.

The Gotenberg error seems to happen often in the users installation. But for me the pdf conversion of ods, xlsx and so on works with httpx as well via paperless ui. I don't have any idea what the problem could be.

**Comment by tb1337** [comment]
That will be refactored in v3 (which is a breaking change). v3 has the possibility to apply a filename to the uploaded document, I am currently implementing that.
